package com.orange.blog.database.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_FRIENDS".
 */
public class UserFriends {

    /** Not-null value. */
    private String selfUUID;
    /** Not-null value. */
    private String friendUUID;
    /** Not-null value. */
    private String friendIP;

    public UserFriends() {
    }

    public UserFriends(String selfUUID, String friendUUID, String friendIP) {
        this.selfUUID = selfUUID;
        this.friendUUID = friendUUID;
        this.friendIP = friendIP;
    }

    /** Not-null value. */
    public String getSelfUUID() {
        return selfUUID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSelfUUID(String selfUUID) {
        this.selfUUID = selfUUID;
    }

    /** Not-null value. */
    public String getFriendUUID() {
        return friendUUID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFriendUUID(String friendUUID) {
        this.friendUUID = friendUUID;
    }

    /** Not-null value. */
    public String getFriendIP() {
        return friendIP;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFriendIP(String friendIP) {
        this.friendIP = friendIP;
    }

}
